# Generated by Django 5.2.8 on 2026-01-25 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(editable=False, help_text='Unique order number generated automatically', max_length=50, unique=True)),
                ('customer_name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('customer_email', models.EmailField(help_text='Email for order confirmation', max_length=254)),
                ('customer_phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('delivery_address', models.TextField(help_text='Full delivery address')),
                ('delivery_date', models.DateField(help_text='Preferred delivery date')),
                ('delivery_notes', models.TextField(blank=True, help_text='Special delivery instructions', null=True)),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe (Credit/Debit Card)'), ('apple_pay', 'Apple Pay'), ('payme', 'PayMe')], default='stripe', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, help_text='Stripe Payment Intent ID for reference', max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before any fees or discounts', max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery/shipping fee', max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total discount amount', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, help_text='Final total amount', max_digits=10)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='orders_orde_created_f0ce29_idx'), models.Index(fields=['order_number'], name='orders_orde_order_n_f3ada5_idx'), models.Index(fields=['customer_email'], name='orders_orde_custome_ca0107_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items ordered')),
                ('line_total', models.DecimalField(decimal_places=2, help_text='Total for this line (quantity × price)', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(help_text='The order this item belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(help_text='The product being ordered', on_delete=django.db.models.deletion.PROTECT, to='products.product')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['id'],
            },
        ),
    ]
