# Generated by Django 5.2.8 on 2026-01-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderitem_product_price_alter_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(help_text='Product name at time of order', max_length=255, null=True),
        ),
    ]
