# Generated by Django 5.2.8 on 2026-02-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='Stripe event ID (e.g. evt_1xxxxx)', max_length=255, unique=True)),
                ('event_type', models.CharField(help_text='Stripe event type (e.g. payment_intent.succeeded)', max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True, help_text='When this event was first processed')),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'indexes': [models.Index(fields=['event_id'], name='orders_stri_event_i_3a7b28_idx'), models.Index(fields=['-processed_at'], name='orders_stri_process_d7c31d_idx')],
            },
        ),
    ]
