# Generated by Django 5.2.8 on 2026-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_stripewebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(help_text='Requested delivery date (must be at least 3 days in advance)', null=True),
        ),
    ]
