# Generated by Django 5.2.8 on 2026-02-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe (Credit/Debit Card)'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('payme', 'PayMe'), ('alipay', 'AliPay')], default='card_pay', max_length=20),
        ),
    ]
