# Generated by Django 5.2.8 on 2026-02-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate applied (HKD to USD) if payment was in USD', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_currency',
            field=models.CharField(default='HKD', help_text='Currency used for payment (HKD or USD)', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in USD (for AliPay payments)', max_digits=10, null=True),
        ),
    ]
