# Generated by Django 5.2.8 on 2026-02-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_exchange_rate_order_payment_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='language',
            field=models.CharField(choices=[('zh-HK', 'Traditional Chinese'), ('en', 'English')], default='zh-HK', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card_pay', 'Credit/Debit Card'), ('apple_pay', 'Apple Pay'), ('google_pay', 'Google Pay'), ('payme', 'PayMe'), ('alipay', 'AliPay'), ('wechat_pay', 'WeChat Pay')], default='card_pay', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_usd',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount in USD (for AliPay / WeChat Pay payments)', max_digits=10, null=True),
        ),
    ]
