# Generated by Django 5.2.8 on 2026-03-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_order_language_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_district",
            field=models.CharField(
                blank=True, help_text="Delivery district", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_region",
            field=models.CharField(
                blank=True,
                help_text="Delivery region (e.g., Hong Kong Island, Kowloon, New Territories)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("card_pay", "Credit/Debit Card"),
                    ("apple_pay", "Apple Pay"),
                    ("google_pay", "Google Pay"),
                    ("payme", "PayMe"),
                    ("whatsapp", "WhatsApp"),
                    ("alipay", "AliPay"),
                    ("wechat_pay", "WeChat Pay"),
                ],
                default="card_pay",
                max_length=20,
            ),
        ),
    ]
