# Generated by Django 5.2.8 on 2026-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_align_total_usd_db_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate (unused, kept for backwards compatibility)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_currency',
            field=models.CharField(default='HKD', help_text='Currency used for payment (HKD)', max_length=3),
        ),
    ]
