# Generated by Django 5.2.8 on 2026-03-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0013_order_delivery_district_order_delivery_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="option_name",
            field=models.CharField(
                blank=True,
                help_text="Selected product option name",
                max_length=100,
                null=True,
            ),
        ),
    ]
