# Generated by Django 5.2.8 on 2026-03-20 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_option_name'),
        ('orders', '0015_rename_total_usd_to_total_cny'),
    ]

    operations = [
    ]
