# Generated by Django 5.2.8 on 2026-03-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0016_merge_20260320_0004"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="deceased_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the deceased person",
                max_length=255,
                null=True,
            ),
        ),
    ]
