# Generated by Django 5.2.8 on 2026-01-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_hot_seller",
            field=models.BooleanField(default=False),
        ),
    ]
