# Generated by Django 5.2.8 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_productcategory_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.AddField(
            model_name="productcategory",
            name="sort_order",
            field=models.IntegerField(default=0),
        ),
    ]
