# Generated by Django 5.2.8 on 2026-03-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategory",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="categories/"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="logo_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="name_en",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
