# Generated by Django 5.2.8 on 2026-03-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_remove_suitablelocation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="url",
        ),
    ]
