# Generated by Django 5.2.8 on 2026-03-29 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_drop_productimage_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcategory",
            name="logo_url",
        ),
    ]
