# Generated by Django 5.2.8 on 2026-03-31 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_remove_logo_url_from_productcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductCategoryMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="products.productcategory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_memberships",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "unique_together": {("product", "category")},
            },
        ),
    ]
